version: "3"

services:
  webserver:
    build:
      context: "./php${PHP_VERSION}"
      dockerfile: "Dockerfile"
      args:
        USER: ${USER}
        UID: ${UID}
        LARAVEL_PORT: ${LARAVEL_PORT}
    container_name: 'lampp-php${PHP_VERSION}'
    restart: unless-stopped
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      COMPOSER_MEMORY_LIMIT: -1
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${LARAVEL_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${PHP_TMP_DIR}:/usr/local/tmp
  mysql:
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    container_name: 'lampp-mysql5.7'
    links:
      - webserver
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/initdb/wordpress.sql:/docker-entrypoint-initdb.d/init2.sql
      - ./mysql/initdb/magento.sql:/docker-entrypoint-initdb.d/init3.sql
      - ./mysql/initdb/laravel.sql:/docker-entrypoint-initdb.d/init4.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "lampp-phpmyadmin"
    depends_on:
      - mysql
    restart: unless-stopped
    links:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
      PMA_PMADB: ${PMA_PMADB}
      PMA_CONTROLUSER: ${PMA_USER}
      PMA_CONTROLPASS: ${PMA_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    volumes:
      - /sessions
      - ${PHPMYADMIN_PHP_INI}:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
  redis:
    container_name: 'lampp-redis'
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
